### ISSUE TITLE
Please enable 10.13

### ISSUE THREAD

**Issue by gingerbeardman** [yimingliu/reverse-image-search-safari#1]
I built the code myself targeting 10.13 and it works just fine. 👍

**Comment by yimingliu** [comment]
Thanks, that's good to know.  I've set minimum macOS target to 10.13 and rebuilt the binary release.  The reason I didn't before is that I don't have any 10.13 machines to test with, and can't really respond to any bug reports if someone has issues with it.

If you do run into problems, let me know, but I'd be hard pressed to find a machine to reproduce any 10.13-specific issues.

**Comment by gingerbeardman** [comment]
Works fine, thanks!

I don't plan to move to 10.14 at all, so I'll keep an eye on it.
