### ISSUE TITLE
How do I get you paid for this?

### ISSUE THREAD

**Issue by galaxy-nomad** [yimingliu/reverse-image-search-safari#12]
Thanks so much for this. Working in latest Catalina with latest Safari 13. I think the folks over at Sidetree lost their minds and became sick with greed. They are charging $10 a pop for old extensions which used to be free. I'd like to donate to you for providing this incredible and effective app free of charge. Do you have a paypal?

**Comment by yimingliu** [comment]
To be fair, Sidetree's app seems to have way more features than this extension.  But yeah, I was basically motivated by the same problem.  If all you're looking for is to right-click on an image to start a search engine query, that price point is ... a bit much.

I didn't imagine I'd have any users besides myself.  But by all means, if you'd like to chip in a few bucks toward my Apple developer license cost, my paypal email is `pertinax at gmail.com` - replace ` at ` with `@`  Much appreciated!

**Comment by yimingliu** [comment]
Received donation.  Thank you very much!  While I'd work on this project whether anyone else used it or donated or not, the kind gesture is very encouraging, and I very much appreciate it.  As always, feel free to raise issues here if you run into any problems.

**Comment by quantumgolem** [comment]
@yimingliu I apologize that I can't financially donate, but I wanted to express my gratitude and say that this is such a cool app. I really appreciate your making this.
