### ISSUE TITLE
On macOS Catalina, extension occasionally fails to respond

### ISSUE THREAD

**Issue by yimingliu** [yimingliu/reverse-image-search-safari#13]
Having just upgraded to macOS Catalina and Safari 13.0.4, it seems that sometimes after Safari is open for an extended period of time, the extension's background process disappears and is not revived by Safari.  From the user's perspective, the symptoms are:

-  choosing one of the reverse image search context menu options ("Search with Google"), etc., no longer works
- Also, even if the user has disabled some search engines in the containing app, all the options still show up when right-clicking

The short-term fix is to close and re-open Safari, which restores the extension process for a while.  A longer-term workaround I am testing is to create a dummy toolbar button that does nothing (you can even toss the button off your Safari toolbar after it installs).  For whatever reason, the inclusion of this toolbar button seems to work around the problem, and the process no longer gets killed.

It seems very similar to the issue reported in #2, only for Catalina. 

If anyone else is experiencing this problem, please do leave a comment on this issue.

**Comment by gingerbeardman** [comment]
After reporting #2 I had this with other extensions, notably https://github.com/fphilipe/PageExtender.app. My experience was on High Sierra (Safari 11 & 12) and Mojave (Safari 12 and 13).

Rather than long running time for Safari, it seemed to happen when I passed the threshold of 50 tabs open. Does that match your experience?

I now use https://github.com/otzbergnet/tabCount (co-developed by me) to keep track of open tabs and avoid the problem (and also helps keep track of Safari using way too much memory). I can have Safari open for a very long time and it doesn't happen.

**Comment by gingerbeardman** [comment]
Oh, and how did you arrive at the workaround?

**Comment by yimingliu** [comment]
#2 and #13 seem to share symptoms (that is, the underlying app extension process is dead or uncommunicative), but the underlying cause might be different.  I'm not willing to say that they can be worked around in the same way, however.  The problem in #2 may still have to be worked around using the tabCount system.  My personal workflow is such that that I have never breached a 50-tab count, so I'd have to test that separately.

My observation so far is this: Safari spawns the extension process every time you open up a page that extension has access to, and despawns it when you leave.  In Activity Monitor, it'd be called something like `Reverse Image Search (Safari)`.  Through observation, it seems like in Catalina, this process may get de-spawned after a while even if the page is still open -- and in certain circumstances still unclear to me, it never gets respawned again (not even if I tick the extension off and on again in Preferences).  Without that process active, any part of the extension that depends on communicating with native code just fails.

Meanwhile, all the extensions that have toolbar buttons have their processes active and around, while my extensions (like the Remove Google Redirection extension, for example) were no longer functional after a while.  So as a test, I've installed useless toolbar buttons.

I'm giving this workaround a few weeks to test.  It might just be a false correlation, too.

**Comment by yimingliu** [comment]
This issue is now presumably outdated.  I may remove the silly toolbar button workaround in the next version, but I want to test this myself for a while first.
