### ISSUE TITLE
Add Yandex image search engine

### ISSUE THREAD

**Issue by radozd** [yimingliu/reverse-image-search-safari#14]
URL would be like this:
https://yandex.ru/images/search?source=collections&rpt=imageview&url=URL

**Comment by yimingliu** [comment]
Yandex search should already have been added to the latest version ( https://github.com/yimingliu/reverse-image-search-safari/releases )

Please upgrade to the latest release and see if it works for you.  You may have to delete the previous version and reinstall the latest one for it to take effect.

**Comment by radozd** [comment]
Oh, I didn't see anything about Yandex in version history.
It's working. Thanks!

**Comment by yimingliu** [comment]
I do need to start writing better version history.  And update the README to say there are other search engines implemented.  There used to be only one or two users besides myself, so I've been lazy about explaining changes.

Good to know it works.  Feel free to file another issue if you run into bugs with it.
