### ISSUE TITLE
Open search tabs in background?

### ISSUE THREAD

**Issue by macsen0** [yimingliu/reverse-image-search-safari#19]
An option for this would be nice.

**Comment by yimingliu** [comment]
https://github.com/yimingliu/reverse-image-search-safari/releases/tag/1.3.1

Haven't tested it much.  Let me know if it works for you

**Comment by macsen0** [comment]
Just gave it a spin, and it works great! Thanks.

**Comment by yimingliu** [comment]
Great!  Feel free to open a new issue if you run into any problems.
