### ISSUE TITLE
Adding KarmaDecay image search

### ISSUE THREAD

**Issue by yourmomdatestedcruz** [yimingliu/reverse-image-search-safari#20]
http://karmadecay.com

I'm unfortunately not very useful or helpful at coding so all I can really tell you is this:
KarmaDecay lets you search by uploading an actual image, or by pasting a URL.

I'd like to be able to right click an image, select the Search on KarmaDecay option and have a new background tab with the results page.
Let me know if I can help or be more specific

**Comment by yimingliu** [comment]
https://github.com/yimingliu/reverse-image-search-safari/releases/tag/1.3.3

Added KarmaDecay.  If you want it to open in background tab, tick the "Open search result in background" option in the containing app.

Let me know if it works for you.

**Comment by yourmomdatestedcruz** [comment]
Thanks for your fast reply!
Works like a charm!

**Comment by yimingliu** [comment]
Great to hear!  As always, feel free to open new issues if anything comes up.
