### ISSUE TITLE
event.target.src isn't working when the img attribute is srcset

### ISSUE THREAD

**Issue by itaz1** [yimingliu/reverse-image-search-safari#21]
consider using event.target.currentSrc since currentSrc is good for both src and (selected) srcset.

**Comment by yimingliu** [comment]
https://github.com/yimingliu/reverse-image-search-safari/releases/tag/1.3.4 

Thank you for pointing this out. Let me know if this fix works.

**Comment by itaz1** [comment]
Works great.
thanks!
