### ISSUE TITLE
Google doesn't seem to work. 

### ISSUE THREAD

**Issue by theday1smine** [yimingliu/reverse-image-search-safari#23]
The google reverse search no longer seems to work. 

All others do however! And they work great!

Thanks for making this!

**Comment by yimingliu** [comment]
Thank you for the bug report!  Looks like Google rebranded Image Search to Lens, and changed the way images are submitted to the service.  

I have a fix now -- https://github.com/yimingliu/reverse-image-search-safari/releases/tag/1.3.6 -- please give it a try and see if Google works for you.

**Comment by yimingliu** [comment]
I've been using the new version for a while and Google seems to be working now.  I'm going to assume that this is fixed, and close the issue accordingly.  Feel free to file a new issue if it doesn't work for you still.
