### ISSUE TITLE
Allow user to choose which searches to activate

### ISSUE THREAD

**Issue by gingerbeardman** [yimingliu/reverse-image-search-safari#7]
For example, I may never use Bing image search so I do not want to see it.

**Comment by yimingliu** [comment]
This selection feature is implemented, along with the requested image search engines, in the latest release ( https://github.com/yimingliu/reverse-image-search-safari/releases/tag/1.1a1 ).  Feel free to give that a try.  I've been using it for a few days and it seemed stable enough.

I've also rebuilt the Xcode project file by remaking the project -- maybe that was the source of the issue that caused you to be unable to build the project?  Not sure, but worth a shot.

**Comment by gingerbeardman** [comment]
Yes, I've been using it since release. Works well.
