### ISSUE TITLE
More uniform context menu labelling

### ISSUE THREAD

**Issue by gingerbeardman** [yimingliu/reverse-image-search-safari#9]
I would like to suggest a change for the labelling in the context menus. I can create a new issue and/or PR.

Currently:
- Google This Image
- Bing This Image
- Yandex This Image
- TinEye This Image
- Ukiyo-e This Image

Suggested:
- Search Image with Google
- Search Image with Bing
- Search Image with Yandex
- Search Image with TinEye
- Search Image with Ukiyo-e

I find these more readable as they are more obviously grouped/related in the context menu.

I will file PR for this shortly.

**Comment by gingerbeardman** [comment]
PR https://github.com/yimingliu/reverse-image-search-safari/pull/10

I also re-ordered the context menu items into alphabetical order. So:

- Search Image with Bing
- Search Image with Google
- Search Image with TinEye
- Search Image with Ukiyo-e
- Search Image with Yandex

In the container app the checkboxes are not alphabetically ordered, I did not know an easy way to get things ordered when using a NSDictionary.

**Comment by yimingliu** [comment]
> In the container app the checkboxes are not alphabetically ordered, I did not know an easy way to get things ordered when using a NSDictionary.

Yep, definitely on the TODO list.  Thanks for putting up the PR!  Will tackle that and implementing sorting, as soon as I get some free time again.

**Comment by gingerbeardman** [comment]
As always, no pressure or rush on this from my side!

**Comment by yimingliu** [comment]
I've provided a build for this now, in https://github.com/yimingliu/reverse-image-search-safari/releases.  Sorry for the latency -- the recent holidays were rather distracting.

Unfortunately this particular build also has a rather user-unfriendly workaround for a weird bug that I'm personally experiencing on Catalina - https://github.com/yimingliu/reverse-image-search-safari/issues/13.  If you'd prefer that I provide a clean build that only has the newly renamed and alphabetized context menus and no stray toolbar button to toss, I can do so on a separate branch.

**Comment by gingerbeardman** [comment]
I don't mind the workaround, thanks for the continued work on this!
